django-blog/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup', views.signup_view, name="signup"),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name="logout"),
]

django-blog/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create', views.create_article, name="create"),
    path('<slug:slug>', views.article_detail, name="detail"),
]

django-blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', article_views.article_list, name="home"),
    path('about/', views.about),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-blog/accounts/models.py
from django.db import models

# Create your models here.

django-blog/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return self.title

    def snippet(self):
        return self.body[:50] + ('...' if len(self.body) > 50 else "")

django-blog/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

django-blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # Log user in
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Log user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):

    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

django-blog/articles/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):

    articles = Article.objects.all().order_by('date')
    # return HttpResponse(articles[0].body)
    return render(request, 'articles/article_list.html', {'articles': articles})

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article':article})

@login_required(login_url="/accounts/login")
def create_article(request):

    if request.method == "POST":
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            article = form.save(commit=False) # Don't save it, first attach user then save it
            article.author = request.user
            article.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    
    return render(request, 'articles/create_article.html', {'form': form})

django-blog/blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homePage(request):
    return HttpResponse("Home Page")

def about(request):
    return render(request,'about.html')

django-blog/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}

<h1>Login</h1>

<form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}

    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}" />
    {% endif %}
    <input type="submit" value="Login"/>
</form>

{% endblock %}

django-blog/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Sign Up</h1>
<form class="site-form" action="/accounts/signup" method="post">
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Signup"/>
</form>
{% endblock %}

django-blog/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="article-detail">
  <div class="article">
    <img src="{{ article.thumb.url }}">
    <h2>{{ article.title }}</h2>
    <p>{{ article.body }}</p>
    <p>{{ article.date }}</p>
    <p>By {{ article.author }}</p>
  </div>
</div>

{% endblock %}

django-blog/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}

<h2>Article List</h2>
<div class="articles">
    {% for article in articles %}
    <div class="article">
        <h3><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h3>
        <p>{{ article.snippet }}</p>
        <p>{{ article.date }}</p>
        <p class="author">{{ article.author.username }}</p>
    </div>
    {% endfor %}
</div>
        
{% endblock %}

django-blog/articles/templates/articles/create_article.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Create an Awesome Article Here</h1>
<form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Create">
</form>

<script src="/static/slugify.js"></script>
{% endblock  %}

django-blog/templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        
        <h1>About Page</h1>
    </body>
</html>

django-blog/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Articles</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href=" {% url 'home' %} "> <img src=" {% static 'logo.png' %}" /> </a></h1>
            {% comment %} {% if not user.is_anonymous %}
                <div>{{ user }}</div>
            {% endif %} {% endcomment %}
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}

            {% endblock %}
        </div>
        
    </body>
</html>